apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-data-store
spec:
  template:
    spec:
      containers:
      - name: rust-data-store
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 256Mi
