apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-telemetry
spec:
  template:
    spec:
      containers:
      - name: python-telemetry
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
