# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_store.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'data_store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61ta_store.proto\x12\tdatastore\"=\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x13\n\x0bttl_seconds\x18\x03 \x01(\x03\"/\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"<\n\x0bGetResponse\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x12HealthCheckRequest\"7\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8b\x02\n\x10\x44\x61taStoreService\x12\x34\n\x03Set\x12\x15.datastore.SetRequest\x1a\x16.datastore.SetResponse\x12\x34\n\x03Get\x12\x15.datastore.GetRequest\x1a\x16.datastore.GetResponse\x12=\n\x06\x44\x65lete\x12\x18.datastore.DeleteRequest\x1a\x19.datastore.DeleteResponse\x12L\n\x0bHealthCheck\x12\x1d.datastore.HealthCheckRequest\x1a\x1e.datastore.HealthCheckResponseB4Z2github.com/username/ci-cd-pipeline/proto/datastoreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/username/ci-cd-pipeline/proto/datastore'
  _globals['_SETREQUEST']._serialized_start=31
  _globals['_SETREQUEST']._serialized_end=92
  _globals['_SETRESPONSE']._serialized_start=94
  _globals['_SETRESPONSE']._serialized_end=141
  _globals['_GETREQUEST']._serialized_start=143
  _globals['_GETREQUEST']._serialized_end=168
  _globals['_GETRESPONSE']._serialized_start=170
  _globals['_GETRESPONSE']._serialized_end=230
  _globals['_DELETEREQUEST']._serialized_start=232
  _globals['_DELETEREQUEST']._serialized_end=260
  _globals['_DELETERESPONSE']._serialized_start=262
  _globals['_DELETERESPONSE']._serialized_end=312
  _globals['_HEALTHCHECKREQUEST']._serialized_start=314
  _globals['_HEALTHCHECKREQUEST']._serialized_end=334
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=336
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=391
  _globals['_DATASTORESERVICE']._serialized_start=394
  _globals['_DATASTORESERVICE']._serialized_end=661
# @@protoc_insertion_point(module_scope)
