apiVersion: v1
kind: Service
metadata:
  name: rust-data-store
  labels:
    app: rust-data-store
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  selector:
    app: rust-data-store
