apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-api-gateway
  namespace: default
spec:
  mode: one
  selector:
    labelSelectors:
      app: go-api-gateway
  stressors:
    memory:
      workers: 4
      size: "256MB"
  duration: "30s"
