apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-rust-store
  namespace: default
spec:
  action: delay
  mode: one
  selector:
    labelSelectors:
      app: rust-data-store
  delay:
    latency: "200ms"
    jitter: "20ms"
  duration: "30s"
