apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-rust-store
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: rust-data-store
  duration: "10s"
