apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
  data:
  - secretKey: log-level
    remoteRef:
      key: api-gateway
      property: log_level
  - secretKey: data-store-target
    remoteRef:
      key: api-gateway
      property: data_store_target
