apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: python-telemetry-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: python-telemetry-secrets
    creationPolicy: Owner
  data:
  - secretKey: log-level
    remoteRef:
      key: python-telemetry
      property: log_level
  - secretKey: argocd-webhook-url
    remoteRef:
      key: python-telemetry
      property: argocd_webhook_url
  - secretKey: slack-webhook-url
    remoteRef:
      key: python-telemetry
      property: slack_webhook_url
